name: Docker Image CI

on:
  schedule:
    - cron: '0 0 * * *' # 每天构建
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone biliup
      run: git clone https://github.com/biliup/biliup.git

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up date-time variable
      id: vars
      run: echo "DATETIME_TAG=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./biliup
        file: ./biliup/Dockerfile
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/biliup:latest
          ${{ secrets.DOCKER_USERNAME }}/biliup:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/biliup:${{ env.DATETIME_TAG }}

    - name: Logout from Docker Hub
      run: docker logout
