name: Docker Image CI

on:
  schedule:
    - cron: '0 0 * * *' # 每小时运行一次
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Microsoft-Rewards-Script repository
      run: git clone https://github.com/TheNetsky/Microsoft-Rewards-Script

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Check for changes in Microsoft-Rewards-Script
      id: check_changes
      run: |
        cd Microsoft-Rewards-Script
        if git diff --quiet HEAD~1; then
          echo "No changes detected in Microsoft-Rewards-Script."
          echo "continue=false" >> $GITHUB_ENV
        else
          echo "Changes detected in Microsoft-Rewards-Script."
          echo "continue=true" >> $GITHUB_ENV
        fi

    - name: Set timezone to UTC+8
      if: env.continue == 'true'
      run: sudo ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" | sudo tee /etc/timezone

    - name: Set up date-time variable
      if: env.continue == 'true'
      id: vars
      run: echo "DATETIME_TAG=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Build and push Docker image
      if: env.continue == 'true'
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./Microsoft-Rewards-Script
        file: ./Microsoft-Rewards-Script/Dockerfile
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/rewards-bot:latest
          ${{ secrets.DOCKER_USERNAME }}/rewards-bot:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/rewards-bot:${{ env.DATETIME_TAG }}

    - name: Logout from Docker Hub
      if: env.continue == 'true'
      run: docker logout
